export enum AUTH_ENDPOINTS {
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  REFRESH = 'REFRESH',
  VALIDATE = 'VALIDATE',
  LOGOUT = 'LOGOUT',
}

export enum SESSION_ENDPOINTS {
  REFRESH = 'REFRESH',
  VALIDATE = 'VALIDATE',
}

export enum PASSWORD_ENDPOINTS {
  FORGOT = 'FORGOT',
  UPDATE = 'UPDATE',
}

export enum HEALTH_ENDPOINTS {
  HEALTH = 'HEALTH',
}

export enum USER_ENDPOINTS {
  DELETE = 'DELETE',
  STATISTICS = 'STATISTICS',
  PROFILE = 'PROFILE',
}

export enum RECENT_GAMES_ENDPOINTS {
  RECENT_GAMES = 'RECENT_GAMES',
  STATS = 'STATS',
}
