[project]
name = "squabble-backend"
version = "0.1.0"
requires-python = ">=3.14"

dependencies = ["pyjwt>=2.13.0"]

[tool.ruff]
line-length = 88

[tool.fastapi]
entrypoint = "main:app"

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["app"]

[dependency-groups]
dev = ["aiosqlite>=0.22.1", "bcrypt>=5.0.0", "fastapi[standard]>=0.141.1"]
