import { cva } from 'class-variance-authority'

export const typography = cva('not-italic select-none', {
  variants: {
    text: {
      h1: 'text-[24px] font-[400] leading-[30px] tracking-[0.48px]',
      h2: 'text-[22px] font-[400] leading-[24px] tracking-[0.44px]',
      h3: 'text-[20px] font-[400] leading-[22px] tracking-[0.4px]',
      h2Medium: 'text-[22px] font-[700] leading-[26px] tracking-[0.44px]',
      caption: 'text-[14px] font-[4i00] leading-[16px] tracking-[0.28px]',
      captionMedium: 'text-[14px] font-[700] leading-[14px] tracking-[0.28px]',
      body: 'text-[16px] font-[400] leading-[16px] tracking-[0.32px]',
      bodyBold: 'text-[16px] font-[700] leading-[16px] tracking-[0.32px]',
      small: 'text-[12px] font-[400] leading-[14px] tracking-[0.24px]',
      smallBold: 'text-[12px] font-[700] leading-[14px] tracking-[0.24px]',
      tiny: 'text-[10px] font-[400] leading-[12px] tracking-[0.2px]',
      tinyBold: 'text-[10px] font-[700] leading-[12px] tracking-[0.2px]',
      custom: '',
    },
    color: {
      white: 'text-text',
      black: 'text-black',
      blue: 'text-background-blue',
      background: 'text-background',
      foreground: 'text-foreground',
      card: 'text-card',
      cardForeground: 'text-card-foreground',
      popover: 'text-popover',
      popoverForeground: 'text-popover-foreground',
      primary: 'text-primary',
      primaryForeground: 'text-primary-foreground',
      secondary: 'text-secondary',
      secondaryForeground: 'text-secondary-foreground',
      muted: 'text-muted',
      mutedForeground: 'text-muted-foreground',
      accent: 'text-accent',
      accentForeground: 'text-accent-foreground',
      destructive: 'text-destructive',
      destructiveForeground: 'text-destructive-foreground',
      border: 'text-border',
      input: 'text-input',
      ring: 'text-ring',
      elevated: 'text-elevated',
      tileCorrect: 'text-tile-correct',
      tileCorrectForeground: 'text-tile-correct-foreground',
      tilePresent: 'text-tile-present',
      tilePresentForeground: 'text-tile-present-foreground',
      tileAbsent: 'text-tile-absent',
      tileAbsentForeground: 'text-tile-absent-foreground',
      success: 'text-success',
      warning: 'text-warning',
      chart1: 'text-chart-1',
      chart2: 'text-chart-2',
      chart3: 'text-chart-3',
      chart4: 'text-chart-4',
      chart5: 'text-chart-5',
      sidebar: 'text-sidebar',
      sidebarForeground: 'text-sidebar-foreground',
      sidebarPrimary: 'text-sidebar-primary',
      sidebarPrimaryForeground: 'text-sidebar-primary-foreground',
      sidebarAccent: 'text-sidebar-accent',
      sidebarAccentForeground: 'text-sidebar-accent-foreground',
      sidebarBorder: 'text-sidebar-border',
      sidebarRing: 'text-sidebar-ring',
    },
    bold: {
      true: 'font-bold',
    },
    medium: {
      true: 'font-medium',
    },
    uppercase: {
      true: 'uppercase',
    },
    capitalize: {
      true: 'capitalize',
    },
    font: {
      default: 'font-general',
    },
  },
  defaultVariants: {
    font: 'default',
    text: 'caption',
    color: 'primary',
  },
})
